INSERT INTO book (title, description, author, isbn, printyear) VALUES ('На ферме', 'Детская история из будней', 'Аркадий Кудряшов', '978-5-287-213', 2017);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Виноват ли нуль?', 'Первая книга малыша.', 'Олег Киров', '978-4-9587-223', 2013);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Тиби на прогулке', 'Рассказ про слоненка Тиби из Африки', 'Василий Петров', '913-2-9587-233', 2010);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Фэнтэзи 3214', 'Научно-фантастическая книга', 'Ирина Токмакова', '978-5-9247-12', 2012);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Я - сам!', 'Книга стихов Яснова Михаила', 'Михаил Яснов', '978-5-9287-282', 2017);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Братство Кольца', 'Хоббит с друзьями в путешествие', 'Дж. Р. Р. Толкина', '5-05-000746-1', 1990);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Две крепости', 'Хоббиты идут в Мордор', 'Дж. Р. Р. Толкина', '5-05-000746-2', 1991);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Путешествия Гулливера', 'Краткое описание книги', 'Джонатан Свифт', '5-05-000746-4', 1993);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Алиса в стране чудес', 'Краткое описание книги', 'Льюис Кэрролл', '5-05-000746-6', 1995);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Двадцать тысяч лье под водой', 'Краткое описание книги', 'Жюль Верн', '5-05-000746-7', 1996);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Дракула', 'Краткое описание книги', 'Брэм Стокер', '5-05-000746-1', 1999);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Война миров', 'Краткое описание книги', 'Герберт Уэллс', '5-05-000746-1', 2000);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('История будущего', 'Краткое описание книги', 'Айзек Азимов', '5-05-000746-1', 2001);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Звездный десант', 'Краткое описание книги', 'Роберт Хайнлайн', '5-05-000746-1', 2002);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Слэн', 'Краткое описание книги', 'Альфред Элтон Ван-Вогт', '5-05-00746-14', 2003);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Джон Уиндэм', 'Краткое описание книги', 'День триффидов', '5-05-00076-15', 2004);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Страсти по Лейбовицу', 'Краткое описание книги', 'Уолтер Миллер', '5-05-0746-16', 2005);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Мальвиль', 'Краткое описание книги', 'Робер Мерль', '5-05-00076-17', 2006);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Я, робот', 'Краткое описание книги', 'Айзек Азимов', '5-05-0746-18', 2007);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Нейромант', 'Краткое описание книги', 'Уильям Гибсон', '5-05-0746-20', 2009);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Космическая Битва', 'Краткое описание книги', 'Артур Кларк', '5-05-0746-21', 2010);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Парк Юрского периода', 'Краткое описание книги', 'Майкл Крайтон', '5-05-0046-22', 2011);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Парк Юрского периода', 'Краткое описание книги', 'Майкл Крайтон', '5-05-000746-22', 2012);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int4', 'Краткое описание книги', 'Author of book5', '5-05-0756-21', 2003);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int0', 'Краткое описание книги', 'Author of book61', '5-05-056-21', 2008);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int8', 'Краткое описание книги', 'Author of book62', '5-05-0546-21', 2002);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int7', 'Краткое описание книги', 'Author of book64', '5-05-0756-21', 2005);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int4', 'Краткое описание книги', 'Author of book65', '5-05-07216-21', 1992);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int2', 'Краткое описание книги', 'Author of book66', '5-05-0745-21', 1995);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int3', 'Краткое описание книги', 'Author of book36', '5-05-0766-21', 1996);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int4', 'Краткое описание книги', 'Author of book65', '5-05-0742-21', 1997);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int5', 'Краткое описание книги', 'Author of book612', '5-05-03346-21', 1993);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int2', 'Краткое описание книги', 'Author of book651', '5-05-07436-23', 1992);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int3', 'Краткое описание книги', 'Author of book613', '5-05-0746-22', 1998);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int4', 'Краткое описание книги', 'Author of book651', '5-05-0746-21', 2000);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int2', 'Краткое описание книги', 'Author of book651', '5-05-0746-21', 2001);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int', 'Краткое описание книги', 'Author of book654', '5-05-0746-23', 2003);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Test book valueOf int3', 'Краткое описание книги', 'Author of book61', '5-05-0746-21', 2004);